---
name: Octo STS

branding:
  color: purple
  icon: git-merge

inputs:
  octo-sts-domain:
    description: The domain of the Octo STS instance to use to federate
    required: false
    default: octo-sts.dev

outputs: {}

runs:
  using: composite
  steps:
    - name: Check if .github/analytical-platform/octo-sts.json exists
      id: check_octo_sts_config_exists
      shell: bash
      run: |
        if [[ ! -f ".github/analytical-platform/octo-sts.json" ]]; then
          echo ".github/analytical-platform/octo-sts.json not found, skipping Octo STS"
          exit 0
        fi

    - name: Run octo-sts
      id: run_octo_sts
      shell: bash
      env:
        INPUT_DOMAIN: ${{ inputs.octo-sts-domain }}
      run: |
        # Loop over .github/analytical-platform/octo-sts.json
        jq -c '.[]' .github/analytical-platform/octo-sts.json | while read -r item; do
          scope=$(echo "${item}" | jq -r '.scope')
          identity=$(echo "${item}" | jq -r '.identity')
          branch=$(echo "${item}" | jq -r '.branch')

          echo "Processing [ scope: ${scope},  identity: ${identity} ]"

          echo "Requesting token"
          INPUT_SCOPE="${scope}" INPUT_IDENTITY="${identity}" node "${GITHUB_ACTION_PATH}/index.js"

          echo "Cloning repository"
          GH_TOKEN=$(cat /tmp/octo-sts-token) gh repo clone "${scope}" "${GITHUB_WORKSPACE}/${scope}" -- --branch "${branch}" --depth 1
        done
