---
name: Octo STS

branding:
  color: purple
  icon: git-merge

inputs: {}

outputs: {}

runs:
  using: composite
  steps:
    - name: Octo STS
      id: octo_sts
      shell: bash
      run: |
        bash main.sh
