---
name: Octo STS

branding:
  color: purple
  icon: git-merge

inputs: {}

outputs: {}

runs:
  using: composite
  steps:
    - name: Octo STS
      id: octo_sts
      shell: bash
      run: |
        ls -lrta

        gh repo clone octo-sts/action /tmp/octo-sts -- --branch v1.0.0 --depth 1

        ls -lrta /tmp/octo-sts
