---
name: Octo STS

branding:
  color: purple
  icon: git-merge

inputs: {}

outputs: {}

runs:
  using: composite
  steps:
    - name: Octo STS
      id: octo_sts
      shell: bash
      run: |
        ls -lrta

        git clone --depth 1 --branch v1.0.0 https://github.com/octo-sts/action.git /tmp/octo-sts

        ls -lrta /tmp/octo-sts
