---
name: Octo STS
author: Ministry of Justice Analytical Platform (analytical-platform@justice.gov.uk)
description: TBC

branding:
  color: purple
  icon: git-merge

# inputs:
# outputs:

runs:
  using: composite
  steps:
    - name: DEBUG
      run: |
        ls -lrta
