---
name: Octo STS

branding:
  color: purple
  icon: git-merge

inputs: {}

outputs: {}

runs:
  using: composite
  steps:
    - name: Octo STS
      id: octo_sts
      shell: bash
      run: |
        # Check if .github/analytical-platform/octo-sts.json exists
        if [[ ! -f ".github/analytical-platform/octo-sts.json" ]]; then
          echo ".github/analytical-platform/octo-sts.json not found, skipping Octo STS"
          exit 0
        fi

        # Clone octo-sts/action
        gh repo clone octo-sts/action /tmp/octo-sts -- --branch v1.0.0 --depth 1

        # Debug
        ls -lrta /tmp/octo-sts

        # Loop over .github/analytical-platform/octo-sts.json
        jq -c '.[]' example/octo-sts.json | while read -r item; do
          scope=$(echo "${item}" | jq -r '.scope')
          identity=$(echo "${item}" | jq -r '.identity')
          echo "Scope: ${scope}, Identity: ${identity}"
        done

