---
on:
  workflow_call:
    inputs:
      runtime:
        type: string
        required: true
    secrets:
      SNYK_TOKEN:
        required: true

permissions: {}

jobs:
  scan-container:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      pull-requests: write
      security-events: write
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Octo STS
        id: octo_sts
        uses: ministryofjustice/analytical-platform-github-actions/octo-sts@8465086d84a8ae8fb993ef582f00cf13b8ceb9c8 # v7.1.0

      - name: Clean Actions Runner
        id: clean_actions_runner
        uses: ministryofjustice/action-clean-runner@390530713a326ddc099b2114f38dd0f2f8eac6da # v1.1.0
        with:
          confirm: true

      - name: Generate .snyk
        id: generate_snyk_policy
        shell: bash
        env:
          RUNTIME: ${{ inputs.runtime }}
        run: |
          curl --silent --show-error --fail --location "https://raw.githubusercontent.com/ministryofjustice/analytical-platform-airflow-${RUNTIME}-base/main/.snyk" --output "analytical-platform-airflow-${RUNTIME}-base-snyk" || true

          if [[ -f "analytical-platform-airflow-${RUNTIME}-base-snyk" ]]; then
            if [[ ! -f .snyk ]]; then
              mv "analytical-platform-airflow-${RUNTIME}-base-snyk" .snyk
            else
              yq eval-all 'select(fileIndex == 0) *+ select(fileIndex == 1)' .snyk "analytical-platform-airflow-${RUNTIME}-base-snyk" > .snyk.merged
              mv .snyk.merged .snyk
            fi
          fi

      - name: Build
        id: build
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7.0.0
        with:
          context: .
          push: false
          tags: ${{ github.sha }}

      - name: Scan
        id: scan
        continue-on-error: true
        uses: snyk/actions/docker@806182742461562b67788a64410098c9d9b96adb # v0.4.0
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ${{ github.sha }}
          args: --severity-threshold=high --app-vulns --policy-path=.snyk --exclude-app-vulns=false --sarif-file-output=snyk.sarif

      - name: Upload SARIF
        id: upload_sarif
        uses: github/codeql-action/upload-sarif@cb06a0a8527b2c6970741b3a0baa15231dc74a4c # v4.34.1
        if: always() && steps.scan.outcome != 'skipped'
        with:
          sarif_file: snyk.sarif

      - name: Evaluate Scan Result
        id: evaluate_scan_result
        if: steps.scan.outcome == 'failure'
        run: exit 1

      - name: Comment on Scan Success
        id: comment_on_scan_success
        if: steps.scan.outcome == 'success'
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Container scan has passed.'
            })

      - name: Comment on Scan Failure
        id: comment_on_scan_failure
        if: failure() && steps.evaluate_scan_result.outcome == 'failure'
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Container scan has failed, please refer to the [User Guidance](https://user-guidance.analytical-platform.service.justice.gov.uk/services/airflow/index.html#vulnerability-scanning) for more information.'
            })
