---
on:
  workflow_call:
    inputs:
      runtime:
        type: string
        required: true

permissions: {}

jobs:
  scan-container:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Octo STS
        id: octo_sts
        uses: ministryofjustice/analytical-platform-github-actions/octo-sts@8465086d84a8ae8fb993ef582f00cf13b8ceb9c8 # v7.1.0

      - name: Clean Actions Runner
        id: clean_actions_runner
        uses: ministryofjustice/action-clean-runner@390530713a326ddc099b2114f38dd0f2f8eac6da # v1.1.0
        with:
          confirm: true

      - name: Configure AWS Credentials
        id: configure_aws_credentials
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 # v6.0.0
        with:
          aws-region: eu-west-2
          role-to-assume: arn:aws:iam::509399598587:role/snyk-analytical-platform-airflow-container-scanning

      - name: Retrieve AWS Secrets Manager Secrets
        id: retrieve_aws_secrets_manager_secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@3a411b6ec5cace3d626412dd917e7bfeac242cfa # v3.0.0
        with:
          secret-ids: |
            SNYK_TOKEN, snyk/analytical-platform-airflow-container-scanning

      - name: Generate .snyk
        id: generate_snyk_policy
        shell: bash
        env:
          RUNTIME: ${{ inputs.runtime }}
        run: |
          curl --silent --show-error --fail --location "https://raw.githubusercontent.com/ministryofjustice/analytical-platform-airflow-${RUNTIME}-base/main/.snyk" --output "analytical-platform-airflow-${RUNTIME}-base-snyk" || true

          if [[ -f "analytical-platform-airflow-${RUNTIME}-base-snyk" ]]; then
            if [[ ! -f .snyk ]]; then
              mv "analytical-platform-airflow-${RUNTIME}-base-snyk" .snyk
            else
              yq eval-all 'select(fileIndex == 0) *+ select(fileIndex == 1)' .snyk "analytical-platform-airflow-${RUNTIME}-base-snyk" > .snyk.merged
              mv .snyk.merged .snyk
            fi
          fi

      - name: Build
        id: build
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7.0.0
        with:
          context: .
          push: false
          tags: ${{ github.sha }}

      - name: Scan
        id: scan
        uses: snyk/actions/docker@806182742461562b67788a64410098c9d9b96adb # v0.4.0
        continue-on-error: true
        with:
          command: container test
          args: --app-vulns --exclude-base-image-vulns --policy-path=.snyk --fail-on=upgradable --severity-threshold=high  --sarif-file-output=snyk.sarif
          image: ${{ github.sha }}

      - name: Upload SARIF
        id: upload_sarif
        uses: github/codeql-action/upload-sarif@89a39a4e59826350b863aa6b6252a07ad50cf83e # v4.32.4
        with:
          sarif_file: snyk.sarif

      - name: Comment on Scan Success
        id: comment_on_scan_success
        if: steps.scan.outcome == 'success'
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Container scan has passed.'
            })

      - name: Comment on Scan Failure
        id: comment_on_scan_failure
        if: failure() && steps.evaluate_scan_result.outcome == 'failure'
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Container scan has failed, please refer to the [User Guidance](https://user-guidance.analytical-platform.service.justice.gov.uk/services/airflow/index.html#vulnerability-scanning) for more information.'
            })
