---
on:
  workflow_call:

permissions: {}

jobs:
  test-container:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set Up Container Structure Test
        id: setup_container_structure_test
        uses: ministryofjustice/github-actions/setup-container-structure-test@db1a54895bf5fb975c60af47e5a3aab96505ca3e # v18.6.0

      - name: Fetch Container Structure Test
        id: fetch_container_structure_test
        run: |
          curl --silent --show-error --location https://raw.githubusercontent.com/ministryofjustice/analytical-platform-airflow-poc-github-actions/refs/heads/main/assets/container-structure-test/container-structure-test.yml --output container-structure-test.yml

      - name: Build
        id: build
        uses: docker/build-push-action@67a2d409c0a876cbe6b11854e3e25193efe4e62d # v6.12.0
        with:
          context: .
          push: false
          tags: ${{ github.repository }}:${{ github.sha }}

      - name: Test
        id: test
        run: |
          container-structure-test test --config container-structure-test.yml --image ${{ github.repository }}:${{ github.sha }}

      - name: Comment on Test Success
        id: comment_on_test_success
        if: steps.test.outcome == 'success'
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Container test has passed.'
            })

      - name: Comment on Test Failure
        id: comment_on_test_failure
        if: failure() && steps.test.outcome == 'failure'
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Container test has failed, please refer to the [User Guide](https://user-guide.analytical-platform.service.justice.gov.uk/) for more information.'
            })
